// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: schema.proto

package micro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroServiceClient is the client API for MicroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroServiceClient interface {
	TriggerCodeGeneration(ctx context.Context, in *GenCodesRequest, opts ...grpc.CallOption) (*CodeGenSuccess, error)
	ExeSchema(ctx context.Context, in *GenSchemaRequest, opts ...grpc.CallOption) (*GenSchemaResponse, error)
}

type microServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroServiceClient(cc grpc.ClientConnInterface) MicroServiceClient {
	return &microServiceClient{cc}
}

func (c *microServiceClient) TriggerCodeGeneration(ctx context.Context, in *GenCodesRequest, opts ...grpc.CallOption) (*CodeGenSuccess, error) {
	out := new(CodeGenSuccess)
	err := c.cc.Invoke(ctx, "/codegen.MicroService/TriggerCodeGeneration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microServiceClient) ExeSchema(ctx context.Context, in *GenSchemaRequest, opts ...grpc.CallOption) (*GenSchemaResponse, error) {
	out := new(GenSchemaResponse)
	err := c.cc.Invoke(ctx, "/codegen.MicroService/ExeSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroServiceServer is the server API for MicroService service.
// All implementations must embed UnimplementedMicroServiceServer
// for forward compatibility
type MicroServiceServer interface {
	TriggerCodeGeneration(context.Context, *GenCodesRequest) (*CodeGenSuccess, error)
	ExeSchema(context.Context, *GenSchemaRequest) (*GenSchemaResponse, error)
	mustEmbedUnimplementedMicroServiceServer()
}

// UnimplementedMicroServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMicroServiceServer struct {
}

func (UnimplementedMicroServiceServer) TriggerCodeGeneration(context.Context, *GenCodesRequest) (*CodeGenSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerCodeGeneration not implemented")
}
func (UnimplementedMicroServiceServer) ExeSchema(context.Context, *GenSchemaRequest) (*GenSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExeSchema not implemented")
}
func (UnimplementedMicroServiceServer) mustEmbedUnimplementedMicroServiceServer() {}

// UnsafeMicroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroServiceServer will
// result in compilation errors.
type UnsafeMicroServiceServer interface {
	mustEmbedUnimplementedMicroServiceServer()
}

func RegisterMicroServiceServer(s grpc.ServiceRegistrar, srv MicroServiceServer) {
	s.RegisterService(&MicroService_ServiceDesc, srv)
}

func _MicroService_TriggerCodeGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroServiceServer).TriggerCodeGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codegen.MicroService/TriggerCodeGeneration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroServiceServer).TriggerCodeGeneration(ctx, req.(*GenCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicroService_ExeSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroServiceServer).ExeSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codegen.MicroService/ExeSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroServiceServer).ExeSchema(ctx, req.(*GenSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MicroService_ServiceDesc is the grpc.ServiceDesc for MicroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codegen.MicroService",
	HandlerType: (*MicroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerCodeGeneration",
			Handler:    _MicroService_TriggerCodeGeneration_Handler,
		},
		{
			MethodName: "ExeSchema",
			Handler:    _MicroService_ExeSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
